name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container: chef/chefworkstation:21.10.655
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: |
          cookstyle
